packages:
  - apps/*
  - packages/*
  - packages/adapters/*
allowBuilds:
  electron: true
  sharp: true
  workerd: true
  esbuild: true
  embedded-postgres: true
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/darwin-x64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/linux-arm64': true
  '@embedded-postgres/windows-x64': true
verifyDepsBeforeRun: false
